[build]
  command = "npm run build"
  publish = ".next"   # 👈 any non-root folder is fine; 'public' is safe

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 1) HTTP → HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
