[build]
  command = "npm run build"
  publish = ".next"   # 👈 any non-root folder is fine; 'public' is safe

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 1) HTTP → HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# 2) Netlify subdomain → your primary domain (change to your real domain)
[[redirects]]
  from = "https://groveblinds.netlify.app/*"
  to = "groveblinds.netlify.app/:splat"
  status = 301
  force = true
