[build]
  command = "npm run build"
  publish = ".next"   # 👈 any non-root folder is fine; 'public' is safe

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 1) HTTP → HTTPS
[[redirects]]
  from = "http://groveblinds.netlify.app/*"
  to = "https://groveblinds.netlify.app/:splat"
  status = 301
  force = true

# (Optional) catch-all just in case
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
